language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

# Enable travis container based infrastructure
sudo: false

before_script:
    - chmod +x gradlew

script:
    - ./gradlew clean assemble
